name: Node CI

push:
  branches:
    - master

pull_request:
  branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: NPM - Install & Build
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v1.0.1
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      if: github.event_name != 'pull_request'
